### PR TITLE
Update upickle

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by Andrapyre** [comment]
@nafg , thanks for this PR. Unfortunately, the latest upickle version requires an upgrade to Scala `3.4.x` (see https://github.com/com-lihaoyi/upickle/pull/607). It looks like they intend to offer support for the `3.3.x` line eventually, vis-a-vis https://github.com/com-lihaoyi/upickle/pull/607#issuecomment-2265878437. I would prefer to wait for them to support a Scala 3 LTS release before upgrading. 

May I ask what the use case is for this? Do you have a workaround if we don't offer support for the latest upickle version?

**Comment by nafg** [comment]
Upgrading https://github.com/nafg/scalajs-facades/ to sbt-ci-release 1.6 is failing because of eviction errors - my build uses ujson and I already upgraded it. I guess 1.5.x didn't have a transitive dependency of upickle at all?

Workarounds include
 - Silencing the eviction error (I don't know if this would create runtime issues)
 - Downgrading my ujson version
 - Using something other than ujson for my needs

Or I could just wait -- it's not like I need to upgrade for any reason.

Any guess how long it might take?

**Comment by Andrapyre** [comment]
No idea what the timeline is, unfortunately. I will close this PR, since it's not building with `+compile`. Feel free to resubmit when upickle 4.0 supports Scala 3 LTS.

**Comment by nafg** [comment]
upickle 4.0.2 is built with Scala 3.3.4

**Pull request closed without merging**
